cluster-init: true

# Manager Role
disable-apiserver: false
disable-controller-manager: false
disable-scheduler: false

token: lb-cluster-gd

write-kubeconfig-mode: "0644"

tls-san:
  - "10.10.10.100"
  - "foo.lan.homelab"

node-label:
  - "foo=bar"
  - "something=amazing"

# embedded-registry: true

protect-kernel-defaults: true
secrets-encryption: true
kube-apiserver-arg:
  - "admission-control-config-file=/var/lib/rancher/k3s/server/psa.yaml"
  - "audit-log-path=/var/lib/rancher/k3s/server/logs/audit.log"
  - "audit-policy-file=/var/lib/rancher/k3s/server/audit.yaml"
  - "audit-log-maxage=30"
  - "audit-log-maxbackup=10"
  - "audit-log-maxsize=100"
  - "request-timeout=300s"
  - "service-account-lookup=true"
kube-controller-manager-arg:
  - "terminated-pod-gc-threshold=10"
  - "use-service-account-credentials=true"
kubelet-arg:
  - "streaming-connection-idle-timeout=5m"
  - "make-iptables-util-chains=true"
